### ISSUE TITLE
User can register unlimited number of times for a challenge

### ISSUE THREAD

**Issue by gaitonde** [appirio-tech/lc1-project#525]
cmc: https://appirio.my.salesforce.com/a3v50000000DApaAAG

**Comment by indytechcook** [comment]
Challenge Launched: https://www.topcoder.com/direct/contest/detail.action?projectId=30048345

**Comment by indytechcook** [comment]
Done and pushed to dev:  https://github.com/appirio-tech/lc1-challenge-service/pull/45
